# -> PlayNews <- #
## Plays the latest news (Swedish Radio) on a chosen media player.

# /config/configuration.yaml
sensor: !include sensors.yaml
custom_intent: !include custom_intent.yaml
conversation: 

# /config/sensors.yaml
- platform: rest
  resource: http://api.sr.se/api/v2/news/episodes?format=json
  name: "SR Ekot Nyheter"
  value_template: "{{ value_json.episodes[0].downloadpodfile.url }}"
  unique_id: sensor.sveriges_radio_news
  force_update: true
      
# /config/intent_script.yaml
PlayNews:
  action:
    - service: media_player.play_media
      data:
        media_content_id: "{{ states('sensor.sveriges_radio_news') }}"
        media_content_type: music
      target:
         entity_id: media_player.ha		# <--- Change this to your chosen media player

# /config/custom_sentences/sv/PlayNews.yaml	
language: "sv"
intents:
  PlayNews:
    data:
      - sentences:
          - "(starta|spela upp|sätt på|berätta) nyheterna"       
          - "jag vill höra nyheterna" 
          - "nyheter"


	

