# -> SetWakeUpTime <- #
## Sets a alarm clock for waking up

# /config/configuration.yaml 
intent_script: !include intent_script.yaml
automation: !include automation.yaml
conversation: 

input_datetime:
  wakeupalarm:
    name: Wake Up Alarm
    has_date: true
    has_time: true

input_boolean:
  switch_wake_up_alarm:
    name: Wake Up Alarm Switch

timer:
  wakeup:
    duration: "00:00:01"
    restore: true

# /config/intent_script.yaml
SetWakeUpTime:
  action:
    - service: input_datetime.set_datetime
      data:
          time: "{{hours}}:{{minutes}}:00"
      target:
          entity_id: input_datetime.wakeupalarm
    - service: input_boolean.turn_on
      data: {}
      target:
          entity_id: input_boolean.switch_wake_up_alarm            
  speech:
    text: "ställde väckarklockan på {{ hours }}  {{ minutes }}"     
  
# /config/custom_sentences/sv/SetWakeUpTime.yaml	
language: "sv"
intents:
  SetWakeUpTime:
    data:
      - sentences:
          - "(starta|ställ|sätt)  [en] väckarklockan på {hours} [och] {minutes} "          
          - "väck mig klockan {hours} [och] {minutes} "    
lists:
  minutes:
    range:
      from: 0
      to: 60
  hours:
    range:
      from: 0
      to: 24

# /config/automation.yaml
alias: wake_up_alarm
description: ""
trigger:
  - platform: time
    at: input_datetime.wakeupalarm
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.wakeup    
condition:
  - condition: time
    weekday:
      - fri
      - thu
      - wed
      - tue
      - mon
action:
  - service: timer.start
    data: {}
    target:
      entity_id: timer.wakeup
  - service: media_player.volume_set
    data:
      volume_level: 1
    target:
      entity_id: media_player.ha
  - service: media_player.play_media
    data:
      media_content_id: /local/sound/wakeup.mp3
      media_content_type: music
    target:
      entity_id: media_player.ha
  - service: notify.mobile_app_iPhone
    data:
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1
      title: "⚠️ "
      message: VAKNA
  - delay:
      hours: 0
      minutes: 0
      seconds: 4
      milliseconds: 0
  - service: notify.mobile_app_iPhone
    data:
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1
      title: "⚠️ "
      message: VAKNA

